# Generated by Django 5.2.7 on 2025-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, upload_to='project_images/'),
        ),
    ]
